stages:
  - build
  - release

cache:
  paths:
    - .m2/

# need to validate path
maven-build:
  image: python:3.6.8-stretch
  stage: build
  script:
    - grep -v '^#' requirements.txt | xargs -n 1 -L 1 pip install # Enforce the order of the installation
    - python -m unittest discover -s ./tests/unit-tests/

maven-release:
  image: python:3.6.8-stretch
  only:
    - master
  when: manual
  stage: release
  script:
    - grep -v '^#' requirements.txt | xargs -n 1 -L 1 pip install # Enforce the order of the installation
    - python -m unittest discover -s ./tests/unit-tests/
    - ./build_package.sh